rock-paper
VladIttop/js-game pull request #11
Opened 2024-07-01 14:04 UTC by Maxiosss

Перевірь будь ласка і хто робить полоски між іграми?

2024-07-02 16:35 UTC, VladIttop commented
Всі роблять нижні полоски

2024-07-02 16:38 UTC, VladIttop approved these changes
Все добре.

2024-07-02 16:39 UTC, VladIttop requested changes
Добав нижню лінію, а так все добре.

2024-07-03 17:34 UTC, Maxiosss commented
чекни

2024-07-03 17:45 UTC, VladIttop approved these changes

2024-07-03 17:45 UTC, merged