calculator
VladIttop/js-game pull request #18
Opened 2024-07-08 14:01 UTC by Maxiosss

2024-07-08 17:10 UTC, VladIttop requested changes
1. Тобі потрібно огорнути всю секцію в inner-container
2. В обох інпутах тобі потрібен placeholder
3.  В всіх кнопках тобі потрібно поставити type="button"

2024-07-09 14:53 UTC, Maxiosss commented
Дякую,сорі,забув

2024-07-09 14:57 UTC, Maxiosss commented
Можеш вже дивитися

2024-07-09 15:54 UTC, VladIttop approved these changes

2024-07-09 15:54 UTC, merged