Rock paper scss
VladIttop/js-game pull request #21
Opened 2024-07-15 11:32 UTC by Maxiosss

Чекни будь ласка

2024-07-15 18:02 UTC, VladIttop requested changes
1. 30 строка тобі не треба margin-right
2. rock-paper-score__text має бути div там де є 3 тега p
3.  Тобі потрібно вирівняти rock-paper-score__text як на макеті

2024-07-17 16:17 UTC, VladIttop requested changes
rock-paper-score__text має бути div там де є 3 тега p

2024-07-18 17:46 UTC, VladIttop requested changes
Зроби кольори через var а так все добре.

2024-07-19 13:33 UTC, Maxiosss commented
Виправив і поміняв на var

2024-07-19 13:57 UTC, Maxiosss commented
Додав hover,тому можеш вже давати цю гілку на main

2024-07-23 19:37 UTC, VladIttop approved these changes
Все добре, приступай до js

2024-07-23 19:37 UTC, merged