Calculator scss
VladIttop/js-game pull request #25
Opened 2024-07-18 15:44 UTC by Maxiosss

2024-07-18 17:23 UTC, VladIttop requested changes
👍 Все добре але поміняй кольори через :root

2024-07-18 18:02 UTC, Maxiosss commented
Поміняв на var

2024-07-19 14:02 UTC, Maxiosss commented
Додав hover,тому можеш вже давати цю гілку на main

2024-07-24 11:52 UTC, VladIttop approved these changes

2024-07-24 11:52 UTC, merged